### ISSUE TITLE
Temperature and Humidity Sensors from Platform MQTT do no appear

### ISSUE THREAD

**Issue by pplucky** [home-assistant/homebridge-homeassistant#160]
Hello.

In Home Assistant configuration file, I have defined sensors like this:
```
sensor:
  - platform: mqtt
    state_topic: "sensor_sala"
    name: Sala
    unit_of_measurement: '°C'
    retain: true
  - platform: mqtt
    state_topic: "sensor_quarto_diogo"
    name: Temp. Diogo
    unit_of_measurement: '°C'
    retain: true
  - platform: mqtt
    state_topic: "sensor_quarto_diogo"
    name: Hum. Diogo
    unit_of_measurement: '%'
    homebridge_sensor_type: "humidity"
    retain: true
```
Still then, although temperature sensors have unit of measurement 'ºC' and humidity sensors have both unit of measurement '%' and homebridge_sensor_type 'humidity' - as per the documentation, these don't seem to appear in homebridge.

Can this be somehow related to mqtt platform?

Thanks in advance for your help.
