### ISSUE TITLE
MQTT Fan always shows 0%

### ISSUE THREAD

**Issue by jake-b** [home-assistant/homebridge-homeassistant#168]
I have an MQTT Fan configured in HomeAssistant.  Everything works fine in HomeAssistant, and I can control the fan in HomeKit using HomeBridge and the bomebridge-homeassitant plugin

The fan setting, always shows up at 0% however:
![img_6668](https://user-images.githubusercontent.com/1012393/27002594-bc57d9f0-4db3-11e7-9128-9bae2206132a.PNG)

If I change the fan setting using the dehumidifier control panel, the fan setting is properly updated in HomeAssistant, but HomeKit does not update the value and always shows 0%.

I acknowledge there are a lot of components in the chain here (custom MQTT device, homeassistant, homebridge-homeassistant, homebridge, Home.app) so I'm not sure where the problem is specifically... but given that HomeAssistant itself works properly, I think it might be either a homebridge issue or a problem with the homebridge-homeassistant plugin.

**Comment by 1043717432** [comment]
Hi, is this an ordinary fan transformed into a mqtt fan?

**Comment by jake-b** [comment]
The setup is Wemos D1 running custom MQTT firmware that simulates keypresses on the dehumidifier's control panel.  It can simulate a "power button" keypress to turn on and off, and simulate a "fan" keypress to change the fan speed.  Also the Wemos D1 monitors the status lines to be able to read the fan speed and publishes a message when the fan speed changes.  The fan only has 3 settings, high, medium, low.

HomeAssistant device configuration is as follows:
```
fan:
  - platform: mqtt
    name: "Dehumidifier"
    state_topic: "dehumidifier/power/status"
    command_topic: "dehumidifier/power/set"
    payload_on: "ON"
    payload_off: "OFF"
    speed_state_topic: "dehumidifier/fan/status"
    speed_command_topic: "dehumidifier/fan/set"
    payload_low_speed: "low"
    payload_medium_speed: "medium"
    payload_high_speed: "high"
    speeds:
      - low
      - medium
      - high
```

Hope that answers the question.

**Comment by 1043717432** [comment]
@jake-b Hi, are you a DIY FAN?

**Comment by schmittx** [comment]
Closing due to staleness and recent updates to the fan component within this plugin, please re-open or start a new issue if this is still a concern.

**Comment by intractve** [comment]
Having the same issue. HomeKit, (via Homebridge) only shows 50% and 100% as possible speeds and both of those work as expected. It shows the fan as on but at 0% if it is "low" in HASS. And unable to set 25% as the speed via HomeKit. Any ideas?

HASS MQTT Fan Config: 
```
fan:
  - platform: mqtt
    name: "Fan 1"
    command_topic: "room/TheFanController/fan1/cmd"
    state_topic: "room/TheFanController/fan1/stat"
    speed_command_topic: "room/TheFanController/fan1/cmd"
    retain: true
    optimistic: false
    payload_on: "25"
    payload_off: "0"
    payload_low_speed: "25"
    payload_medium_speed: "50"
    payload_high_speed: "100"
    speeds:
      - low
      - medium
      - high
```
