### ISSUE TITLE
Change switch type

### ISSUE THREAD

**Issue by jcastro** [home-assistant/homebridge-homeassistant#175]
Hello!

I've a few zigbee wall switches and they are shown as a switches on HomeKit, however I can edit (inside the Home.app from Apple) the type to switch, light or fan. 

I've tried adding this to my HA configuration in case it was supported (even if is not mentioned on the readme)

```yaml
switch.wall_switch_right_158d00014a9626:
    icon: mdi:lightbulb
    friendly_name: Luz
    homebridge_switch_type: light
```
But no luck! So I was wondering if this could be something possible to add?

Thanks!

![img_5571](https://user-images.githubusercontent.com/190036/27223239-e8fdcd44-528f-11e7-83fa-e9fcbd5d1cbb.jpg)
![img_5572](https://user-images.githubusercontent.com/190036/27223240-e9265b4c-528f-11e7-8919-9b67f0caf3fe.PNG)
