### ISSUE TITLE
Any Sensors and Cover do no appear

### ISSUE THREAD

**Issue by edabm** [home-assistant/homebridge-homeassistant#225]
Home app can use switch and light but can not appear any sensor and cover, i try to define different sensor.
Version: node@v6.11.0  
               homebridge-homeassistant@2.3.1
               homebridge@0.4.28
 configuration.yaml like this:
```
customize:
    cover.mqtt_cover:
        homebridge_cover_type:  garage_door 
    sensor.mqtt_sensor_2:
        homebridge_sensor_type: light 
    sensor.humidity_1:
        homebridge_sensor_type: humidity
sensor :
  - platform: mqtt
    name: "humidity_1"
    state_topic: "home/bedroom/humidity"
    unit_of_measurement: "%"
  - platform: mqtt
    name: "co2_1"
    state_topic: "home/bedroom/co2_1"
    unit_of_measurement: “ppm”
  - platform: mqtt
    state_topic: "home/bedroom/lux_1"
    unit_of_measurement: "lux"
 - platform: mqtt
    name: “Room_Temperture"
    state_topic: "home/room/temp"
    unit_of_measurement: "°C"
    qos: 1
    retain: true
cover:
  - platform: mqtt
    name: "MQTT Cover"
    state_topic: "home/cover"
    command_topic: "home/cover/set"
light:
  -  platform: mqtt_template
    command_topic: "home/rgb1/set"
    command_on_template: "on"
    command_off_template: "off"
```

can you give me some help for mqtt platform? 
Thx :)
 

>
