### ISSUE TITLE
Homebridge color picker sync problem in homeassistant, bulbs stop responding

### ISSUE THREAD

**Issue by badstraw360** [home-assistant/homebridge-homeassistant#266]
Home Assistant release (hass --version):
0.60.0

Python release (python3 --version):
3.5

Component/platform:
light/limitlessled

**Description of problem:**
When I'm using any limitlessled light in homeassistant and try to change bulb colors using the color picker in homekit and save them to use later, homeassistant won't update the color and the bulb stops responding. So even If I try to turn off the bulb in homeassistant after that the bulb stops responding completely and I need to reset the pi to make it work again. 
Here is a video of the problem:
https://vimeo.com/248093143

**Expected:**
Change colors accordingly. 

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```
light:
  platform: limitlessled
  bridges:
    - host: 192.168.0.50
      groups:
      - number: 1
        type: rgbww
        name: lámpara
      - number: 2
        type: rgbww
        name: luz
        fade: on

```
