### ISSUE TITLE
MQTT Fan "low" speed not usable via Homebridge

### ISSUE THREAD

**Issue by intractve** [home-assistant/homebridge-homeassistant#312]
Having a similar issue like [#168](https://github.com/home-assistant/homebridge-homeassistant/issues/168). HomeKit, (via Homebridge) only shows 50% and 100% as possible speeds and both of those work as expected. It shows the fan as on but at 0% if it is "low" in HASS. Any ideas?

HASS MQTT Fan Config: 
```
fan:
  - platform: mqtt
    name: "Fan 1"
    command_topic: "room/TheFanController/fan1/cmd"
    state_topic: "room/TheFanController/fan1/stat"
    speed_command_topic: "room/TheFanController/fan1/cmd"
    retain: true
    optimistic: false
    payload_on: "25"
    payload_off: "0"
    payload_low_speed: "25"
    payload_medium_speed: "50"
    payload_high_speed: "100"
    speeds:
      - low
      - medium
      - high
```
