### ISSUE TITLE
Repeating error

### ISSUE THREAD

**Issue by danichispa** [home-assistant/homebridge-homeassistant#6]
Hi! Since I  updated homebridge to it latest version, I'm getting a lot of errors (well, the same all the time), and now when I tell Siri to turn off all the lights, some of them stay on.
This is the error from homebridge log:
```
TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/homebridge-homeassistant/index.js:115:31
    at Request.onResponse [as _callback] (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:69:9)
    at self.callback (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
/usr/local/lib/node_modules/homebridge-homeassistant/index.js:115
      for (var i = 0; i < data.length; i++) {
```

**Comment by toome123** [comment]
It is needed any additional config for this plugin except
 `"platforms": [
  {
    "platform": "HomeAssistant",
    "name": "HomeAssistant",
    "host": "http://192.168.1.16:8123",
    "password": "yourapipassword",
    "supported_types": ["light", "switch", "media_player", "scene"]
  }
]
`

beacuase i add only this, and after 2 min showing me this "Plugin - DidFinishLaunching
"
is throw the same error as you.. 
it's needed any additional config ? Or is just bug

**Comment by danichispa** [comment]
I ended reinstalling everything, and updating all homebridge stuff, same as node, etc.
I'm error free since May 2nd. Try that.

**Comment by toome123** [comment]
Ok thanks :) , but can you answer to my question please.
t is needed any additional config for this plugin except
"platforms": [ { "platform": "HomeAssistant", "name": "HomeAssistant", "host": "http://192.168.1.16:8123", "password": "yourapipassword", "supported_types": ["light", "switch", "media_player", "scene"] } ]

**Comment by danichispa** [comment]
Sorry, no, no aditional config except that.
This is my config.json from homebridge dir.
```yaml
{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51111,
        "pin": "222-33-444"
    },
    "platforms": [
        {
            "platform" : "HarmonyHub",
            "name" : "Harmony Salon"
        },
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "http://192.168.1.30:8123",
            "password": "password",
            "supported_types": ["light", "scene"]
  }

     ]
}
```
